Repository stegnerw/penguin_swarm, pull requests merged in 2021-04, with the labels that each got.

#13 Issue 11 - Add environment and framework
  .gitignore
  environment.yml
  pylintrc
  src/agent.py
  src/cfg/template.ini
  src/environment.py
  src/main.py
  src/obstacle.py
  src/penguin.py
Labels: enhancement

#18 Thermal model
  src/agent.py
  src/cfg/template.ini
  src/environment.py
Labels: enhancement

#19 Implement the movement policy for our final design
  src/agent.py
  src/cfg/template.ini
  src/environment.py
Labels: enhancement

#21 Issue 20 - Fix bugs and some codestyle after initial implementation
  .gitignore
  environment.yml
  src/agent.py
  src/cfg/template.ini
  src/environment.py
  src/main.py
Labels: bug, enhancement

#23 Add plotting portion of alive agents
  .gitignore
  src/agent.py
  src/cfg/sid_1.ini
  src/environment.py
Labels: enhancement

#24 Thermal update
  src/cfg/template.ini
  src/environment.py
Labels: enhancement

#26 Fix issue where movement policy is not called
  src/agent.py
  src/penguin.py
Labels: bug

#27 Change GIF duration not being `time_step_size`
  src/environment.py
Labels: bug

#29 Add usage
  README.md
Labels: documentation
